apiVersion: v2
name: my-flask-app
description: A Helm chart for Flask on EKS with PostgreSQL
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: 12.5.7
    repository: https://charts.bitnami.com/bitnami
