# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.5.0"
}

resource "null_resource" "prevent_local_apply" {
  lifecycle {
    prevent_destroy = true
  }

  provisioner "local-exec" {
    when    = destroy
    command = "echo 'Local apply is disabled. Use Spacelift!' && exit 1"
  }
}
