name: "Terragrunt CI"

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: 'v0.58.0' # Specify the version you want

      - name: Run Terragrunt Plan
        run: |
          cd path/to/your/project
          terragrunt run-all plan --terragrunt-non-interactive